#!/bin/bash
#oshash=`oshash $1| cut -f1 -d" "`
#identify -format "\"oshash\": \"$oshash\" , %m" $1
size=`du -b $1 | cut -f1`
oshash=`oshash $1| cut -f1 -d" "`
resolution=`identify -verbose $1| grep "Resolution"| cut -f2 -d":"`
#identify -format "{\n  \"image\": [{\n      \"format\":\"%m\",\n      \"geometry\":\"%g\",\n      \"codec\":\"mjpeg\",\n      \"duration\":\"0.040000\",\n      \"pixel_format\":\"yuvj420p\",\n      \"pixel_aspect_ratio\":\"1:1\",\n      \"display_aspect_ratio\":\"259:194\",\n      \"framerate\":\"25:1\",\n      \"extension\":\"%e\",\n      \"width\":\"%w\",\n      \"height\":\"%h\",\n      \"id\":\"0\",\n      \"resolution\":\"$resolution\",\n      \"compression\":\"%C\",\n      \"colorspace\":\"%[colorspace]\", \n      \"filename\":\"%i\",\n      \"type\":\"%[type]\",\n      \"orientation\":\"%[orientation]\", \n      \"class\":\"%r\",\n      \"depth\": %[depth]\n}],\n  \"oshash\": \"$oshash\",\n  \"size\": $size, \n  \"path\":\"%i\" \n}" $1

#identify -format "{\n  \"image\": [{\n      \"format\":\"%m\",\n      \"codec\":\"mjpeg\",\n      \"duration\":\"0.040000\",\n      \"pixel_aspect_ratio\":\"1:1\",\n      \"display_aspect_ratio\":\"%w:%h\",\n      \"framerate\":\"25:1\",\n      \"extension\":\"%e\",\n      \"width\":\"%w\",\n      \"height\":\"%h\",\n      \"resolution\":\"%wX%h\",\n      \"filename\":\"%i\",\n}],\n  \"oshash\": \"$oshash\",\n  \"size\": $size, \n  \"path\":\"%i\" \n}" $1

identify -format "{\n  \"image\": [{\n      \"format\":\"%m\",\n      \"codec\":\"mjpeg\",\n      \"duration\":\"0.040000\",\n      \"pixel_aspect_ratio\":\"1:1\",\n      \"display_aspect_ratio\":\"%w:%h\",\n      \"framerate\":\"25:1\",\n      \"extension\":\"%e\",\n      \"width\":\"%w\",\n      \"height\":\"%h\",\n      \"resolution\":\"%wX%h\",\n      \"filename\":\"%i\"\n}],\n  \"oshash\": \"$oshash\",\n  \"size\": $size, \n  \"path\":\"%i\" \n}" $1

#identify -format "{\n  \"image\": [{\n      \"codec\":\"mjpeg\",\n      \"duration\":\"0.040000\",\n      \"pixel_format\":\"yuvj420p\",\n      \"pixel_aspect_ratio\":\"1:1\",\n      \"display_aspect_ratio\":\"259:194\",\n      \"framerate\":\"25:1\",\n      \"extension\":\"%e\",\n      \"width\":\"%w\",\n      \"height\":\"%h\",\n      \"id\":\"0\",\n      \n      \"filename\":\"%i\",\n      \"type\":\"%[type]\",\n      \"depth\": %[depth]\n}],\n  \"oshash\": \"$oshash\",\n  \"size\": $size, \n  \"path\":\"%i\" \n}" $1
